### ISSUE TITLE
Part 2 suggestions

### ISSUE THREAD

**Issue by henryiii** [henryiii/bh-talk-pyhep-2020#1]
@HDembinski Here are some suggestions for part 2, overall it is great. I'm working on part 1 and a followup Hist demo - the notebook talks really require too many words in my opinion, but that does make them much better for review later. Also I might try putting some of this in the documentation in the near future, and update the notebook page in the docs with this new content too.

---

top cell: Do you use the "plot" function defined? If not, you can remove it.

---

"not_so_nicely_organised" You are far too nice here. This is still more nicely organized than I would normally see. A more realistic example: 

```python 
data_non_candidates = bh.Histogram(bh.axis.Regular(10, 0, 10, metadata="p_T"),
                     bh.axis.Regular(5, 0, 5, metadata="eta"))
...
```
Or, if you want to be really realistic, these won't have a consistent naming scheme and will be spread around in the code, one will be missing, etc...

Depends on what you want to talk about, though. What you've shown is most correct way to do it, so maybe that parallel is what you are highlighting.

---

```python
all_tracks = nicely_organised.project(0, 1, 3)
```

You might consider (also?) using the inverse:

```python
all_tracks = nicely_organised[:, :, ::sum, :]
```

Instead of having to list all the axis you want to keep, you give the axes you want to sum over (which is exactly how it is described in English just above - you describe what you want to remove, not what you want to keep). Maybe we can try to get the shortcut method you suggested into 0.10.0, so you could write:

```python
all_tracks = nicely_organised[:, :, sum, :]
# or, using the Xarray style dict:
all_tracks = nicely_organised[{2:sum}]
```

I'm going to start calling this dict indexing Xarray style indexing, since they use it to solve a similar problem -  though we came up with it completely independently. :)

---

```python
print(f"mean.count={mean.count} mean.value={mean.value:g} mean.variance={mean.variance:g}")

# Python 3.8:
# print(f"{mean.count=} {mean.value=} {mean.variance=}")
```

We have a virtual environment for Python 3.8, and that'll be on binder, so I'd be fine if you show off the Python 3.8 syntax, with the older syntax as a comment, instead. Up to you.

---

> As a general rule, in Boost-Histogram we give you choices and reasonable defaults . If you need extra accuracy, use Sum. By default, you get normal summation, which is less precise but more performant.

This statement  seems to imply you can turn this accumulator on and off when histogramming, but I don't think you can, the Sum accumulator is always used, correct?

---

I would replace

```python
table.view()[:] = np.minimum(rng.normal(0.7, 0.2, size=(5, 2)), 1)
```

with 

```python
table[...] = np.minimum(rng.normal(0.7, 0.2, size=(5, 2)), 1)
# or
table[:, :] = np.minimum(rng.normal(0.7, 0.2, size=(5, 2)), 1)
```
The single colon is misleading - this is a 2D array, not a 1D array, and furthermore, it is slightly less efficient - you are breaking the array into 1D pieces in Python, then filling them in C, rather than filling whole array at once in C. Then you don't need the view when this is correct.

---

I woud recommend:

```python
tab_view = table.view()
efficiencies = []
for k, m in zip(table.axes[0].index(p), table.axes[1].index(eta)):
    efficiencies.append(tab_view[(k, m)])
```

be replaced with:

```python
tab_view = table.view()
efficiencies = tab_view[table.axes.index(p, eta)]
```

Appending a list is slow - the above is fully vectorized and produces an array instead of a list, and is much more concise.

**Comment by HDembinski** [comment]
> This statement seems to imply you can turn this accumulator on and off when histogramming, but I don't think you can, the Sum accumulator is always used, correct?

You cannot turn it on or off when histogramming, because that wouldn't make sense. Who would fill their histogram with some data accurately, only to fill some other data later to the same histogram in a less accurate way?

What I want to say here is: if you need the fastest possible histogram, we have a solution for you. If you need a very accurate histogram at the cost of some slowdown and memory, we also have something for you. We try not to enforce choices, when there is a significant trade-off between two options. Other tools do not give you these choices.

**Comment by HDembinski** [comment]
> all_tracks = nicely_organised.project(0, 1, 3)

You are right, I should show the sum syntax (I use that mostly myself). Should we remove `.project` in version 1.0? I think it is fully replaced now by UHI syntax, right?

> Appending a list is slow - the above is fully vectorized and produces an array instead of a list, and is much more concise.

I agree with you. I tried something like that first, but I didn't get the right shape (my mistake). But there is an issue when the indices are outside of the range of the table, one has to cut the values first before doing this. But anyway.

**Comment by HDembinski** [comment]
> table[...] = np.minimum(rng.normal(0.7, 0.2, size=(5, 2)), 1)

Nice. See it is good for me to get up to speed with the latest features.

Edit: Why is this syntax not working in the last cell?

Replacing
```
h.view()[:] /= h.axes[0].widths * h.sum()
```
with
```
h /= h.axes[0].widths * h.sum()
```
does not produce an error, but a weird looking wrong result.

And it says 
```
h[:] /= h.axes[0].widths * h.sum()
```
is not implemented yet.

**Comment by henryiii** [comment]
> Should we remove .project in version 1.0? I think it is fully replaced now by UHI syntax, right

No, project does two things UHI does not do. First, it lets you list what you want to keep, instead of what you want sum over. If you want to just get axes 2 for a plot, `.project(2)` is much better than `h[::sum, ::sum, :, ::sum]`. Second, it lets you reorder the axes, `.project(2, 1)` (I think - depends on BH).

**Comment by HDembinski** [comment]
Right, I remember now we already had the discussion. I think `.project` will become obscure though, most people will just use UHI.

**Comment by HDembinski** [comment]
Thank you for the useful comments.

**Comment by henryiii** [comment]
```
h /= h.axes[0].widths * h.sum()
```

really should work, but the hint is (you've just added it above) that `h[:]` doesn't work. I noticed this when going through it and put it on my short to-do list. We'll try to at least understand it or (better) fix it before 0.10.0.

**Comment by henryiii** [comment]
> I think `.project` will become obscure though

That's okay. It's there if people need it, and (hopefully) has a clear docstring. You are only likely to care when you get to 4 or more axes anyway, so it probably will be a power user feature.

**Comment by henryiii** [comment]
3021.2

**Comment by henryiii** [comment]
I left my computer to go eat and Soren sent the message above. His first GitHub comment. :) (He was trying to get a waterfall video to play)

**Comment by HDembinski** [comment]
Hehe

**Comment by henryiii** [comment]
> does not produce an error, but a weird looking wrong result.

Are you sure you didn't just run this twice (since it modifies in-place)? It's passing a test for me.

Edit: But this is what I tried to simplify it to when I went through this the first time, I believe, and it didn't work. Will continue to check.
DoubleEdit: Variable edges may be the trick to getting it to fail a test...

---

> `h[:] /= h.axes[0].widths * h.sum()`

This is hurting by brain... The seemingly logical thing here would be do decompose this to `h.__getitem__(slice(none)).__itruediv__(...)`, but that is incorrect for us (since we make a copy with get item, so modifications on the sliced histogram are ignored), and thankfully, not how Python is handling it. Instead it is calling `h.__setitem__(h.copy())`  which doesn't make sense to me at the moment.

```python
h = bh.Histogram(bh.axis.Regular(10, 0, 1))
h[...] = [0, 1,2,3,4,5,6,7,8,10,11, 12]

dens = h.view().copy() / h.axes[0].widths * h.sum()
h1 = h.copy()

h1[2:10] /=  h.axes[0].widths[2:10] * h.sum()
```

Calls `h.__setitem__(h[2:10])`. Note in all cases, the division hasn't happened yet.

I don't think we'll be able to implement this syntax easily, and maybe not unless we support python allocated memory for histograms.

**Comment by henryiii** [comment]
I should have a PR that fixes the simple case.

**Comment by HDembinski** [comment]
> ```
> h /= h.axes[0].widths * h.sum()
> ```
> 
> really should work,...

You didn't discuss this case. This not giving the right answer is the most problematic issue for me.

**Comment by henryiii** [comment]
Looks good!
